name: ci-cd
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    types:
      - closed
jobs:
  deploy_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add your deployment steps here, such as building and deploying your application
      - name: Deploying Application
        run: echo "Deploying application..."

      # Notify Slack with an interactive message
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: |
            {
              "text": "Có một bản release cần được approve.\nENV: staging\nRepository: ${{ github.repository }}\nGitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "attachments": [
                {
                  "text": "Bạn có đồng ý chấp nhận bản release này ko ?",
                  "fallback": "You are unable to choose a game",
                  "callback_id": "approve_cancel_release",
                  "color": "#3AA3E3",
                  "attachment_type": "default",
                  "actions": [
                    {
                      "name": "cancel",
                      "text": "Cancel",
                      "style": "danger",
                      "type": "button",
                      "value": "cancel",
                      "confirm": {
                        "title": "Are you sure?",
                        "text": "Có chắc là cancel ko ?",
                        "ok_text": "Yes",
                        "dismiss_text": "No"
                      }
                    },
                    {
                      "name": "approved",
                      "text": "approve",
                      "style": "primary",
                      "type": "button",
                      "value": "approved",
                      "confirm": {
                        "title": "Are you sure?",
                        "text": "Có chắc là approve ko ?",
                        "ok_text": "Yes",
                        "dismiss_text": "No"
                      }
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: user1,user2,org-team1
          minimum-approvals: 1
          issue-title: "Deploying v1.3.5 to prod from staging"
          issue-body: "Please approve or deny the deployment of version v1.3.5."
          exclude-workflow-initiator-as-approver: false
          additional-approved-words: ''
          additional-denied-words: ''

  approved:
    needs: deploy_release
    runs-on: ubuntu-latest
    if: github.event_name == 'slack_interactive' && github.event.action.name == 'approve'
    steps:
      - name: Wait for approval
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.repos.createDeploymentStatus({
              ...context.repo,
              deployment_id: context.payload.deployment.id,
              state: 'success',
              log_url: 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}',
              description: 'Deployment approved and in progress.',
              environment_url: 'https://github.com/dungnv-2032/hello-cicd/tree/master'
            })
            return 'approved'

  cancel:
    needs: deploy_release
    runs-on: ubuntu-latest
    if: github.event_name == 'slack_interactive' && github.event.action.name == 'cancel'
    steps:
      - name: Wait for cancelation
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.repos.createDeploymentStatus({
              ...context.repo,
              deployment_id: context.payload.deployment.id,
              state: 'failure',
              log_url: 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}',
              description: 'Deployment canceled.',
              environment_url: 'https://github.com/dungnv-2032/hello-cicd/tree/master'
            })
            return 'canceled'