name: ci-cd
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    types:
      - closed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add your deployment steps here, such as building and deploying your application
      - name: Deploying Application
        run: echo "Deploying application..."

      # Notify Slack with an interactive message
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: |
            {
              "text": "Có một bản release cần được approve.\nENV: staging\nRepository: ${{ github.repository }}\nGitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}\nPlease approved in URL ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: trstringer/manual-approval@v1
        timeout-minutes: 120
        with:
          secret: ${{ github.GIT_TOKEN }}
          approvers: [dungnv-2032]
      - name: Deploy to production
        run: echo deploying
      - name: Wait for approval
        uses: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        with:
          secret: ${{ secrets.GIT_TOKEN }}
          approvers: trstringer

#  approved:
#    needs: deploy_release
#    runs-on: ubuntu-latest
#    if: github.event_name == 'slack_interactive' && github.event.action.name == 'approve'
#    steps:
#      - name: Wait for approval
#        uses: actions/github-script@v5
#        with:
#          github-token: ${{ secrets.GITHUB_TOKEN }}
#          script: |
#            github.repos.createDeploymentStatus({
#              ...context.repo,
#              deployment_id: context.payload.deployment.id,
#              state: 'success',
#              log_url: 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}',
#              description: 'Deployment approved and in progress.',
#              environment_url: 'https://github.com/dungnv-2032/hello-cicd/tree/master'
#            })
#            return 'approved'
