name: ci-cd
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    types:
      - closed
jobs:
  deploy_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add your deployment steps here, such as building and deploying your application
      - name: Deploying Application
        run: echo "Deploying application..."

      # Notify Slack with an interactive message
      - name: Report Status
        uses: slackapi/slack-github-action@v1.22.0
        with:
          channel-id: "C06SM71HT0U"
          payload: |
            {
              "text": "Would you like to play a game?",
              "attachments": [
                  {
                    "text": "Choose a game to play",
                    "fallback": "You are unable to choose a game",
                    "callback_id": "wopr_game",
                    "color": "#3AA3E3",
                    "attachment_type": "default",
                    "actions": [
                      {
                        "name": "game",
                        "text": "Chess",
                        "type": "button",
                        "value": "chess"
                      },
                      {
                        "name": "game",
                        "text": "Falken's Maze",
                        "type": "button",
                        "value": "maze"
                      },
                      {
                        "name": "game",
                        "text": "Thermonuclear War",
                        "style": "danger",
                        "type": "button",
                        "value": "war",
                        "confirm": {
                            "title": "Are you sure?",
                            "text": "Wouldn't you prefer a good game of chess?",
                            "ok_text": "Yes",
                            "dismiss_text": "No"
                        }
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_WEBHOOK }}

  approved:
    needs: deploy_release
    runs-on: ubuntu-latest
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'pending'
    steps:
      - name: Wait for approval
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.repos.createDeploymentStatus({
              ...context.repo,
              deployment_id: context.payload.deployment.id,
              state: 'success',
              log_url: 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}',
              description: 'Deployment approved and in progress.',
              environment_url: 'https://github.com/dungnv-2032/hello-cicd/tree/master'
            })
            return 'approved'

  cancel:
    needs: deploy_release
    runs-on: ubuntu-latest
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'pending'
    steps:
      - name: Wait for cancelation
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.repos.createDeploymentStatus({
              ...context.repo,
              deployment_id: context.payload.deployment.id,
              state: 'failure',
              log_url: 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}',
              description: 'Deployment canceled.',
              environment_url: 'https://github.com/dungnv-2032/hello-cicd/tree/master'
            })
            return 'canceled'